// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vcrdwrrrqigoclbyqjbx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjcmR3cnJycWlnb2NsYnlxamJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxODEwMjUsImV4cCI6MjA3MDc1NzAyNX0.c8XjaOUNfOxlXy7_Ub7P_tEEuB4y7yQyRdiAluR6dPU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});